In [1]:
import dotenv
import os
import requests
import pandas as pd

In [2]:
dotenv.load_dotenv(dotenv.find_dotenv())

API = os.getenv('API')

In [3]:
df = pd.read_parquet("../Dados/BikeData-Processed.parquet")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 15 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   duracao_viagem            1000000 non-null  int64
 1   inicio_viagem             1000000 non-null  datetime64[ns]
 2   fim_viagem                1000000 non-null  datetime64[ns]
 3   id_estacao_inicio         999927 non-null   Int64
 4   nome_estacao_inicio       999927 non-null   category
 5   estacao_inicio_latitude   1000000 non-null  float64
 6   estacao_inicio_longitude  1000000 non-null  float64
 7   id_estacao_fim            999927 non-null   Int64
 8   nome_estacao_fim          999927 non-null   category
 9   estacao_fim_latitude      1000000 non-null  float64
 10  estacao_fim_longitude     1000000 non-null  float64
 11  id_bike                   1000000 non-null  int64
 12  tipo_usuario              1000000 non-null  category
 13  ano_nascimento            1000000 non-null  int64
 14  genero                    1000000 non-null  category
dtypes: Int64(2), category(4), datetime64[ns](2), float64(4), int64(3)
memory usage: 91.6 MB

In [4]:
df.head()

,duracao_viagem,inicio_viagem,fim_viagem,id_estacao_inicio,nome_estacao_inicio,estacao_inicio_latitude,estacao_inicio_longitude,id_estacao_fim,nome_estacao_fim,estacao_fim_latitude,estacao_fim_longitude,id_bike,tipo_usuario,ano_nascimento,genero
0,882,2018-11-25 18:21:38.774,2018-11-25 18:36:21.472,423,W 54 St & 9 Ave,40.765849,-73.986905,476,E 31 St & 3 Ave,40.743943,-73.979661,20049,Customer,1969,Desconhecido
1,669,2018-08-13 18:25:50.544,2018-08-13 18:36:59.968,3467,W Broadway & Spring Street,40.724947,-74.001659,327,Vesey Pl & River Terrace,40.715338,-74.016584,33847,Subscriber,1987,Masculino
2,521,2018-12-18 20:12:15.062,2018-12-18 20:20:57.017,411,E 6 St & Avenue D,40.722281,-73.976687,504,1 Ave & E 16 St,40.732219,-73.981656,30284,Subscriber,1971,Masculino
3,270,2018-05-18 14:23:52.105,2018-05-18 14:28:22.491,437,Macon St & Nostrand Ave,40.680983,-73.950048,3047,Halsey St & Tompkins Ave,40.682369,-73.944118,31542,Subscriber,1964,Masculino
4,441,2018-08-14 19:00:15.867,2018-08-14 19:07:37.052,519,Pershing Square North,40.751873,-73.977706,498,Broadway & W 32 St,40.748549,-73.988084,18363,Subscriber,1979,Masculino

In [5]:
def calculate_distance(LATITUDE1, LONGITUDE1, LATITUDE2, LONGITUDE2, API):
    url = f'https://dev.virtualearth.net/REST/v1/Routes/DistanceMatrix?key={API}&origins={LATITUDE1},{LONGITUDE1}&destinations={LATITUDE2},{LONGITUDE2}&travelMode=driving&distanceUnit=mi'
    response = requests.get(url)
    return response.json()

In [6]:
calculate_distance(40.765849, -73.986905, 40.743943, -73.979661, API)

{'authenticationResultCode': 'ValidCredentials',
 'brandLogoUri': 'http://dev.virtualearth.net/Branding/logo_powered_by.png',
 'copyright': 'Copyright © 2023 Microsoft and its suppliers. All rights reserved. This API cannot be accessed and the content and any results may not be used, reproduced or transmitted in any manner without express written permission from Microsoft Corporation.',
 'resourceSets': [{'estimatedTotal': 1,
   'resources': [{'__type': 'DistanceMatrix:http://schemas.microsoft.com/search/local/ws/rest/v1',
     'destinations': [{'latitude': 40.743943, 'longitude': -73.979661}],
     'origins': [{'latitude': 40.765849, 'longitude': -73.986905}],
     'results': [{'destinationIndex': 0,
       'originIndex': 0,
       'totalWalkDuration': 0,
       'travelDistance': 2.803,
       'travelDuration': 15.5167}]}]}],
 'statusCode': 200,
 'statusDescription': 'OK',
 'traceId': 'b2f22c45890a4418a1c703c38dd964e2|BN0000642D|0.0.0.0|BNZ0017571'}